from .base_model import BaseModel
from .municipality import MunicipalityModel
from .location import LocationModel
from .vehicle import VehicleModel
from .employee import EmployeeModel
from .device_group import DeviceGroupModel
from .device import DeviceModel
from .depot import DepotModel
from .municipalty_depot import MunicipalityDepotModel
