# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotModel',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MunicipalityDepotModel',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_depot', to='e_container.DepotModel')),
                ('municipality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_depot', to='e_container.MunicipalityModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='street_number',
            field=models.CharField(blank=True, help_text='Used for the division of longer streets', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='e_container.MunicipalityModel'),
        ),
        migrations.AddField(
            model_name='depotmodel',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depot', to='e_container.LocationModel'),
        ),
    ]
