# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_container', '0002_auto_20180112_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroupmodel',
            name='last_demand',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
