# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_container', '0003_devicegroupmodel_last_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='capacity',
            field=models.FloatField(default=10, help_text='Unit of measurement is m3'),
        ),
    ]
